### ISSUE TITLE
bug send message, WindowLookup become null

### ISSUE THREAD

**Issue by chuongmep** [weianweigan/RevitLookupWpf#25]
**Describe the bug**
bug send message, WindowLookup become null

**To Reproduce**
1. Go to Snoop method inside
2. Check main WindowLookup it will be become null

**Expected behavior**

**Screenshots**

Maybe problem come from here
[If applicable, add screenshots to help explain your problem.]
(https://github.com/weianweigan/RevitLookupWpf/blob/49093236e479368e1ab6b23d65030d6de43e5b45/RevitLookup/PropertySys/BaseProperty/ReferenceType/ObjectProperty.cs#L27)
if we can't check form main, we can't set owner for form **HelpWindow**, it will null when we click to method or properties snoop and right click goto help, **Help Window** will be not show center **LookupWindow**
https://github.com/weianweigan/RevitLookupWpf/blob/49093236e479368e1ab6b23d65030d6de43e5b45/RevitLookup/ViewModel/LookupViewModel.cs#L136-L139

**Additional context**
![Revit_B3EVDEU40K](https://user-images.githubusercontent.com/31106432/154657175-6cdcb77a-a9f6-4795-b9fd-c508a257c31c.gif)

**Comment by weianweigan** [comment]
The problem should be come here.
(https://github.com/weianweigan/RevitLookupWpf/blob/49093236e479368e1ab6b23d65030d6de43e5b45/RevitLookup/ViewModel/LookupWindowViewModel.cs#L97-L123)

In line105 ,i new a lookupviewmodel to store and display data. Because search command is binding to LookupData , so it cause a null exception.

I will pass _lookupwindow as a parameter.
(https://github.com/weianweigan/RevitLookupWpf/blob/6a2eefe2acf993090926f16222b7377f49135e8f/RevitLookup/ViewModel/LookupWindowViewModel.cs#L97-L123)

**Comment by chuongmep** [comment]
This is a remarkable one, I will look carefully next time
